### ISSUE TITLE
Using Comments

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/bapi-p3-the-scoop#2]
I would recommend using comments in your code to give some context.  Commenting is very important, especially when working on shared code bases as it allows those who are unfamiliar to get the general gist of what is happening, allowing them to modify it much faster.  I would recommend giving overarching comments to the function methods that you included as well as inline comments within those functions for anything that wouldn't be readily apparent to a viewer.

**Comment by mohaldev** [comment]
That makes sense. Will incorporate the habit.
