### ISSUE TITLE
Leveraging ES6 Syntax

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/bapi-p3-the-scoop#3]
You did a good job using ES6 syntax in your functions.  There were some areas where you could have leveraged it.  The following function illustrates this:

https://github.com/mohaldev/bapi-p3-the-scoop/blob/c4add1d5eca940c9fee7ed4ff6f50f93d4ae5374/ServerFileOnly/server.js#L307-L322

In this function you have a variable called "savedComment".  Later on your set it as the value within an object with a key of "comment".  To make this less verbose, you could have made the variable name "comment" and leveraged ES6 to be able to change the object from

```
{ comment: savedComment }
```
to

```
{ comment }
```

It isn't huge, but it does cut down on the syntax a bit.  Just a tip.

**Comment by mohaldev** [comment]
Thanks
