### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/bapi-p3-the-scoop#4]
Overall, you did a good job with this project.  Your formatting was clean and made it easily readable.  You also leveraged ES6 syntax well and seemed to create every method that was required.  I would recommend adding some comments to your functions to add further clarification to them.  Also, in the future, I would recommend uploading all of the files that come with the project.  By only uploading the server file, there is no way to run the tests against your code to ensure that it was implemented properly.  Otherwise, good job.

**Comment by mohaldev** [comment]
Thanks, Tom. The reason to upload the server.js file was that the normal upload doesn't allow more than 25MB and the project is much more than that. 

If you can feed this back to Codecademy, that would be great as well.

Thanks for the review and have a great day.
